version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: react-use
    versions:
    - 17.2.1
    - 17.2.3
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.10
    - 7.13.14
  - dependency-name: jschardet
    versions:
    - 2.3.0
  - dependency-name: workbox-window
    versions:
    - 6.0.2
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: rxjs
    versions:
    - 6.6.6
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.15
    - 7.12.17
    - 7.13.2
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: eslint-plugin-flowtype
    versions:
    - 5.2.0
    - 5.2.1
    - 5.2.2
    - 5.3.0
    - 5.3.1
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
    - 0.145.0
  - dependency-name: "@babel/preset-flow"
    versions:
    - 7.12.1
