version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    enabled: false
  complex-logic:
    config:
      threshold: 9
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 250
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    enabled: false
  similar-code:
    config:
      threshold: 75
  identical-code:
    config:
      threshold: 55