language: node_js
node_js:
  - "node"
  - "lts/*"
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
branches:
  except:
  - netlify