name: Build and tests

on:
  push:
    branches: [ master ]
    tags:
      - '!*' # Do not execute on tags
    paths:
      - src/**
      - public/**
      - cypress/**
      - '.github/**'
      - '**.json'
      - '**.js'
      - '**.jsx'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Get cypress cache directory
        id: cypress-cache-dir
        run: |
          echo "::set-output name=dir::$(npm run cypress:cachepath)"
      - name: Persist cypress cache
        uses: actions/cache@v3
        id: cypress-cache
        with:
          path: ${{ steps.cypress-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Prepare Code-Climate reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - run: npm ci
      - name: Run tests and report coverage
        env:
          CC_TEST_REPORTER_ID: 1ba79968e72f466436bec94526c2234b000886463638859d328819c94bfe3590
        run: |
          npm test
          ./cc-test-reporter after-build --exit-code $?
